version: '3.9'

services:
  api_dev:
    build:
      context: ./api
      target: dev
      args:
        - UID=${UID}
        - GID=${GID}
        - USER=${USER}
    user: "${UID}:${GID}"
    container_name: api_dev
    ports:
      - "0.0.0.0:8080:8080"
    volumes:
      - ./api:${HOME}/app
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
      - $SSH_AUTH_SOCK:/ssh-agent
    environment:
      SSH_AUTH_SOCK: /ssh-agent
    working_dir: ${HOME}/app
    tty: true

  web_dev:
    build:
      context: ./web
      target: dev
      args:
        - UID=${UID}
        - GID=${GID}
        - USER=${USER}
    user: "${UID}:${GID}"
    container_name: web_dev
    ports:
      - "0.0.0.0:3000:3000"
    volumes:
      - ./web:${HOME}/app
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
      - $SSH_AUTH_SOCK:/ssh-agent
    environment:
      SSH_AUTH_SOCK: /ssh-agent
    working_dir: ${HOME}/app
    tty: true

  db_dev:
    build:
      context: ./db
      target: db
    container_name: db_dev
    ports:
      - "0.0.0.0:3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: pweb
      MARIADB_USER: ${USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      TZ: 'Asia/Tokyo'

  dbeaver:
    build:
      target: dbeaver
      context: ./db
    container_name: dbeaver
    depends_on:
      - db_dev
    environment:
      - DBEAVER_USER=${USER}
      - DBEAVER_PASSWORD=${MARIADB_PASSWORD}
      - DBEAVER_HOST=db_dev
      - DBEAVER_PORT=3306
      - DBEAVER_DATABASE=pweb
      - TZ=Asia/Tokyo
    ports:
      - "8978:8978"
